export const PostsActionTypes = {
  CREATE_NEW_POST: 'CREATE_NEW_POST',
  DELETE_POST: 'DELETE_POST',
  PUBLISH_POST: 'PUBLISH_POST',
  UNPUBLISH_POST: 'UNPUBLISH_POST',
  SET_CURRENT_POST: 'SET_CURRENT_POST',
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',
};
